#!/usr/bin/env bash

show_help() {
	cat <<-'EOF'
		Usage: rbm [-o <newbase>] [-u <upstream>]
		For all branches run  git rebase <upstream> <branch> [--onto <newbase>]
		Use master for upstream if non is provided.
EOF
}

newbase=
upstream=master
failed_branches=
failed_branches_num=0

while getopts ":ho:u:" opt; do
	case "$opt" in
		h)
			show_help
			exit 0
			;;
		o) newbase=$OPTARG
			;;
		u) upstream=$OPTARG
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done
shift "$((OPTIND-1))"

orig_branch="$(git rev-parse --abbrev-ref @)"
[ "$orig_branch" = HEAD ] && orig_branch="$(git rev-parse @)"
[ -n "$newbase" ] || newbase="$upstream"

# Check for unstaged changes
# TODO: Check only for unstaged changes not uncommitted
if [ -n "$(git status --porcelain -uno)" ]; then
	echo >&2 'Commit or stash changes before rebase.'
	exit 1
fi

branches="$(git for-each-ref --format='%(refname)' refs/heads 2>/dev/null)"

for branch in $branches; do
	branch="${branch#refs/heads/}"
	[ "$branch" = "$upstream" ] && continue
	[ "$branch" = "$newbase" ] && continue
	printf 'Rebasing %s ' "$branch"
	if git rebase "$upstream" "$branch" --onto "$newbase" >/dev/null 2>&1; then
		tput setaf 2 0 0
		echo '(ok)'
		tput sgr0
	else
		git rebase --abort
		tput setaf 1 0 0
		echo '(failed)'
		tput sgr0
		: "$(( failed_branches_num+=1 ))"
		failed_branches="$failed_branches $branch"
	fi
done

if [ $failed_branches_num -eq 0 ]; then
	git checkout "$orig_branch"
elif [ $failed_branches_num -eq 1 ]; then
	# If only one branch failed to rebase, offer to rebase interactively
	printf >&2 'Rebase %s interactively? [y/N] ' "$failed_branches"
	read -r resp
	case "${resp:-n}" in
		Y*|y*)
			git rebase -i master "$failed_branches"
			;;
		N*|n*)
			git checkout "$orig_branch"
			;;
	esac
else
	# TODO: Select repo to rebase
	printf '%s\n' "$failed_branches"
	git checkout "$orig_branch"
fi
